### ISSUE TITLE
Error projection using Maxent

### ISSUE THREAD

**Issue by isisarantes** [biomodhub/biomod2#21]
Hello,

I'm having this issue and I don't know how to fix it.
Everything is up to date (R, packages, java, maxent).
 
```
> ##PROJECTION 
> presBiomodProj_od <- BIOMOD_Projection(modeling.output = myBiomodModelOut_od,
+                                     new.env = current,
+                                     proj.name = 'current',
+                                     selected.models = 'all',
+                                     binary.meth = 'ROC',
+                                     filtered.meth = 'TSS',
+                                     compress = 'xz',
+                                     build.clamping.mask = T,
+                                     do.stack=T)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Models Projections -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

> Building clamping mask

> Projecting Od_PA1_RUN1_MAXENT.Phillips ...Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file.
```
Any ideias how to fix it?
Thank you in advance!
Ísis Arantes

**Comment by gsilvaarias** [comment]
Hello,

I am also having an issue projecting MAXENT models.

```
Schi_Proj <- BIOMOD_Projection(modeling.output=Schi_models,
                               new.env=current,
                               proj.name='Schi_current',
                               selected.models='all',
                               binary.meth='TSS',
                               compress='gzip',
                               clamping.mask=F,
                               keep.in.memory=T,
                               output.format='.img')
```

Here the output message:
```
-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Models Projections -=-=-=-=-=-=-=-=-=-=-=-=-=-=

	> Building clamping mask

*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
	> Projecting Schi_PA1_RUN1_GLM ...
	> Projecting Schi_PA1_RUN1_GAM ...
	> Projecting Schi_PA1_RUN1_GBM ...
	> Projecting Schi_PA1_RUN1_CTA ...
	> Projecting Schi_PA1_RUN1_MARS ...
	> Projecting Schi_PA1_RUN1_RF ...
	> Projecting Schi_PA1_RUN1_ANN ...
	> Projecting Schi_PA1_RUN1_MAXENT.Phillips ...Error in .local(.Object, ...) : 

In addition: Warning message:
In system(command = maxent.command, wait = TRUE, intern = TRUE) :
  running command 'java -mx4096m -cp "/data/home/users/g.silvaarias/local/bin/maxent.jar" density.Project "Schi/models/Schi/Schi_PA1_RUN1_MAXENT.Phillips_outputs/Schi_PA1_RUN1.lambdas" "Schi/./m_25170024/part1" "Schi/./m_25170024/part1/projMaxent.asc"  doclamp=false visible=false autorun nowarnings notooltips' had status 1
Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file. (file does not exist)
Calls: BIOMOD_Projection ... lapply -> FUN -> FUN -> .local -> .rasterObjectFromFile
Execution halted
```

I would appreciate any advice.

All the best,
Gustavo

**Comment by DamienGeorges** [comment]
Hi,
Are you still facing this issue?
Do you have ay reproducible example to share with me?

**Comment by momeni133** [comment]
Same problem here. I am receiving the same error for maxent

**Comment by chenqh0618** [comment]
I got the same error, too. It only occurs for maxent.

**Comment by chenqh0618** [comment]
> I got the same error, too. It only occurs for maxent.

I have tried diffrerent version of MaxEnt, but didn't work.

**Comment by pleopersica** [comment]
> Hi,
> Are you still facing this issue?
> Do you have ay reproducible example to share with me?

Dear Dr. George, I am stuck with my analysis due to the same issue as mentioned above for many months now. Could you tell us some probable solutions to resolve it?

**Comment by DamienGeorges** [comment]
Could you try to install the latest github release of biomod2 and give it a new try please?
Any amelioration?

**Comment by chenqh0618** [comment]
Thanks，
installing biomod2 package of github version seems working.
and now no error reported from my data.

**Comment by dan-mich** [comment]
Hi,
I am facing the same issue. I installed the latest github release of biomod2 and the latest maxent, but the problem persists. Here is the script

```
models_proj_2060_SSP245 <- BIOMOD_Projection(modeling.output = all_models,new.env = vars_2060,proj.name = my_proj_name ,path_to_maxent.jar = "G:/Publications/PREY_PREDATOR/maxent.jar", binary.meth = "TSS",do.stack = FALSE, build.clamping.mask =  FALSE)
```

and the output message in debugging mode


```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Models Projections -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

	> Projecting Natrix.natrix_PA1_RUN1_GLM ...
		Writing projection on hard drive...
	> Projecting Natrix.natrix_PA1_RUN1_GAM ...
		Writing projection on hard drive...
	> Projecting Natrix.natrix_PA1_RUN1_MAXENT.Phillips ...Error in .local(.Object, ...) : 

In addition: Warning message:
In system(command = maxent.command, wait = TRUE, intern = TRUE) :
  running command 'java -mx512m -cp "G:\Publications\PREY_PREDATOR/maxent.jar" density.Project "Natrix.natrix/models/biotic_present/Natrix.natrix_PA1_RUN1_MAXENT.Phillips_outputs/Natrix.natrix_PA1_RUN1.lambdas" "Natrix.natrix/./m_11330025/part1" "Natrix.natrix/./m_11330025/part1/projMaxent.asc"  doclamp=false visible=false autorun nowarnings notooltips' had status 1
Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file. (file does not exist)

Enter a frame number, or 0 to exit   

 1: BIOMOD_Projection(modeling.output = all_models, new.env = vars_2060, proj.name = my_proj_name, path_to_maxent.jar = "G:/Publicat
 2: lapply(selected.models, function(mod.name) {
    cat("\n\t> Projecting", mod.name, "...")
    BIOMOD_LoadModels(modeling.output,
 3: FUN(X[[i]], ...)
 4: predict(mod, new.env, on_0_1000 = on_0_1000, filename = filename, omit.na = omit.na, split.proj = split.proj)
 5: predict(mod, new.env, on_0_1000 = on_0_1000, filename = filename, omit.na = omit.na, split.proj = split.proj)
 6: .local(object, ...)
 7: .predict.MAXENT.Phillips_biomod2_model.RasterStack(object, newdata, silent = TRUE, ...)
 8: lapply(file.path(unlist(MWD$m_workdir), "projMaxent.asc"), raster, RAT = FALSE, crs = projection(newdata))
 9: FUN(X[[i]], ...)
10: FUN(X[[i]], ...)
11: .local(x, ...)
12: .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer", ...)
```

My session info:
```
sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    
system code page: 1253

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gbm_2.1.8      rgdal_1.5-18   dismo_1.3-3    usdm_1.1-18    plyr_1.8.6     biomod2_3.4.13 raster_3.4-5   sp_1.4-4      

loaded via a namespace (and not attached):
 [1] tidyr_1.1.2           viridisLite_0.3.0     splines_4.0.3         foreach_1.5.1         prodlim_2019.11.13   
 [6] Formula_1.2-4         stats4_4.0.3          latticeExtra_0.6-29   ENMeval_0.3.1         ipred_0.9-9          
[11] pillar_1.4.7          backports_1.2.1       lattice_0.20-41       glue_1.4.2            pROC_1.16.2          
[16] RColorBrewer_1.1-2    checkmate_2.0.0       randomForest_4.6-14   colorspace_2.0-0      recipes_0.1.15       
[21] Matrix_1.2-18         timeDate_3043.102     pkgconfig_2.0.3       maxnet_0.1.2          PresenceAbsence_1.1.9
[26] earth_5.3.0           caret_6.0-86          purrr_0.3.4           scales_1.1.1          jpeg_0.1-8.1         
[31] gower_0.2.2           lava_1.6.8.1          TeachingDemos_2.12    tibble_3.0.4          mgcv_1.8-33          
[36] mda_0.5-2             generics_0.1.0        ggplot2_3.3.2         ellipsis_0.3.1        withr_2.3.0          
[41] nnet_7.3-14           hexbin_1.28.1         rasterVis_0.49        survival_3.2-7        magrittr_2.0.1       
[46] crayon_1.3.4          doParallel_1.0.16     nlme_3.1-149          MASS_7.3-53           class_7.3-17         
[51] data.table_1.13.4     tools_4.0.3           lifecycle_0.2.0       stringr_1.4.0         munsell_0.5.0        
[56] plotrix_3.7-8         compiler_4.0.3        tinytex_0.27          rlang_0.4.9           plotmo_3.6.0         
[61] grid_4.0.3            iterators_1.0.13      rstudioapi_0.13       gtable_0.3.0          ModelMetrics_1.2.2.2 
[66] codetools_0.2-16      abind_1.4-5           reshape_0.8.8         reshape2_1.4.4        R6_2.5.0             
[71] zoo_1.8-8             lubridate_1.7.9.2     dplyr_1.0.2           stringi_1.5.3         parallel_4.0.3       
[76] Rcpp_1.0.5            vctrs_0.3.6           rpart_4.1-15          png_0.1-7             tidyselect_1.1.0     
[81] xfun_0.19 
```

I could not pinpoint the problem, but hopefully it will help somebody else. 

All the best!
Danai

**Comment by DamienGeorges** [comment]
Installing the latest version of biomod2 available on github should fix this issue:
`devtools::install_github('biomodhub/biomod2')`

**Comment by acoconis** [comment]
I am having the same issue, but installing the latest version did not fix it. Any other suggestions?
