### ISSUE TITLE
Error in { :    task 2 failed - "task 1 failed - "task 1 failed - "object 'tuned.mod' not found"""

### ISSUE THREAD

**Issue by colin123-tt** [biomodhub/biomod2#455]
When I'm using the function （BIOMOD_Modeling （OPT.strategy = 'tuned'））The following error occurs：Error in { :    task 2 failed - "task 1 failed - "task 1 failed - "object 'tuned.mod' not found"""

**Comment by MayaGueguen** [comment]
Hello Colin,

Could you provide a bit more information please ?
- what is the output of `sessionInfo()` ?
- what is your code, starting from the beginning to when you get the error ?
- have you run it without parallelisation (setting `nb.cpu` arguments to 1) ? do you get the same error ?

Maya

**Comment by colin123-tt** [comment]
以下是我的代码
[biomod.txt](https://github.com/biomodhub/biomod2/files/15290830/biomod.txt)
I think I have parallel running checked.

**Comment by MayaGueguen** [comment]
Thank you.

Could you send me the ouptut of the following commands please ?

- `summary(myBiomodData)`
- `show(myBiomodData)`
- `plot(myBiomodData)`

Maya

**Comment by colin123-tt** [comment]
No problem. 
[myBiomodData.txt](https://github.com/biomodhub/biomod2/files/15291213/myBiomodData.txt)

**Comment by MayaGueguen** [comment]
Do you have the plot please ?
Also, what is the output of the command `sessionInfo()` please ?

**Comment by colin123-tt** [comment]
![1715587349986](https://github.com/biomodhub/biomod2/assets/131012452/481f07e0-c23c-4106-ba8e-f8e2806175d8)
[sessionInfo().txt](https://github.com/biomodhub/biomod2/files/15291268/sessionInfo.txt)

**Comment by MayaGueguen** [comment]
Thank you Colin :pray: 

I see that you seem to have the `4.2-5` biomod2 version, but did you updated it recently ?
We just pushed the `4.2-5` onto CRAN, and Hélène did a great job correcting some errors, especially concerning modeling options and tuning.
Could you then try and update your version, either from CRAN or github ?
```
install.packages(biomod2) ## CRAN

library(devtools)
install_github("biomodhub/biomod2") ## GITHUB
```
They should be the same at this time :) 

Then, if you could try runinng again your code ?

**Comment by colin123-tt** [comment]
I re-updated my software as you did, but it is still having this problem, here is the output of my command
[BIOMOD_Modeling.txt](https://github.com/biomodhub/biomod2/files/15291625/BIOMOD_Modeling.txt)

**Comment by chenyongpeng1** [comment]
Hello，Everyone:
        I only used MAXENT and OPT.strategy = 'tuned' , The same errors occur,I think that the Windows and Maxent model are incompatible. 
Error in summary.connection(connection) : invalid connection
In addition: Warning message:
In bm_RunModelsLoop(bm.format = bm.format, weights = weights, calib.lines = calib.lines,  :
  Parallelisation with `foreach` is not available for Windows. Sorry.

**Comment by MayaGueguen** [comment]
Hello Colin and Cheyong,

Hélène found out the origin of the problem :eyes: It seems that it is actually due to some hidden clusters / connections that are opened by the ENMeval tuning process for MAXENT that are not closed afterwards, and it is occurring only on Windows.
She just pushed a commit on github with the correction, you can try and install it with : 
```
library(devtools)
install_github("biomodhub/biomod2")
```

Maya

**Comment by chenyongpeng1** [comment]
> Hello Colin and Cheyong,
> 
> Hélène found out the origin of the problem 👀 It seems that it is actually due to some hidden clusters / connections that are opened by the ENMeval tuning process for MAXENT that are not closed afterwards, and it is occurring only on Windows. She just pushed a commit on github with the correction, you can try and install it with :
> 
> ```
> library(devtools)
> install_github("biomodhub/biomod2")
> ```
> 
> Maya


Sorry，I can not download “biomod2” package from github.
devtools::install_github("biomodhub/biomod2", dependencies = TRUE)
Using GitHub PAT from the git credential store.
Downloading GitHub repo biomodhub/biomod2@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/biomodhub/biomod2/tarball/HEAD' failed

**Comment by chenyongpeng1** [comment]
> > Hello Colin and Cheyong,
> > Hélène found out the origin of the problem 👀 It seems that it is actually due to some hidden clusters / connections that are opened by the ENMeval tuning process for MAXENT that are not closed afterwards, and it is occurring only on Windows. She just pushed a commit on github with the correction, you can try and install it with :
> > ```
> > library(devtools)
> > install_github("biomodhub/biomod2")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maya
> 
> Sorry，I can not download “biomod2” package from github. devtools::install_github("biomodhub/biomod2", dependencies = TRUE) Using GitHub PAT from the git credential store. Downloading GitHub repo biomodhub/biomod2@HEAD Error in utils::download.file(url, path, method = method, quiet = quiet, : download from 'https://api.github.com/repos/biomodhub/biomod2/tarball/HEAD' failed

 I have installed it, but it still occur error.
-=-=-=--=-=-=- youcha_allData_allRun_MAXENT 

		Creating Maxent Temp Proj Data...Error in { : task 1 failed - "cannot open the connection"
In addition: Warning messages:
1: executing %dopar% sequentially: no parallel backend registered 
2: In file(con, "r") :
  cannot open file './youcha/models/1716170262/youcha_PA1_RUN1_MAXENT_outputs/maxent.stderr': Permission denied
3: In file(con, "r") :
  cannot open file './youcha/models/1716170262/youcha_allData_allRun_MAXENT_outputs/maxent.stderr': Permission denied

Best wishes!

**Comment by colin123-tt** [comment]
Yes, I think it is the problem of manent, when I put manent at the end, all the models can run normally，Then I used the following code to close the background parallel cluster and the subsequent steps can run normally.
#cl <- makeCluster(2)
#registerDoParallel(cl)
#on.exit(stopCluster(cl))
Thank you for your patient reply, I hope you get better and better！cheers！🍺

**Comment by chenyongpeng1** [comment]
Good job！ cheers！

**Comment by K0BE248** [comment]
> 干得好！干杯！

你好，请问您是怎么解决的呢，我出现的跟您一样的问题，谢谢

**Comment by K0BE248** [comment]
> Good job！ cheers！
hello，Chen，
Could you tell me how you resolved the "Permission denied" issue with maxent.stderr? I encountered the same problem after running my code, which caused the entire model output to fail to display. I would love to discuss this with you. My email is 1501948230@qq.com, and I hope to hear from you. Best regards.

**Comment by yuliaUU** [comment]
i have the same issue on mac with the biomod4.2-5-2 or 4.2-6-1 versions, when i tune any model after tunning  MAXENT, i get the same error message
```
# Tuning for MAXENT model
  tuned.maxent <- bm_Tuning(model = "MAXENT",
                            tuning.fun = "avNNet",
                            do.formula = TRUE,
                            bm.options = myBiomodOptions@options$MAXENT.binary.MAXENT,
                            bm.format = myBiomodData,
                            metric.eval = "auc.val.avg"  
  )
```

**Comment by MayaGueguen** [comment]
Hello Yulia,

If I remember correctly, it seems that the **ENMeval** tuning function used for `MAXENT` might be opening new clustering threads on your computer when running... And I thought we add those command lines within the code package to get rid of this issue :thinking:  
Do you still get the error if, after tuning `MAXENT`, you run the following lines before running another tuning ? :eyes: 
```
cl <- makeCluster(2)
registerDoParallel(cl)
on.exit(stopCluster(cl))
```

Maya

**Comment by Alexromer2** [comment]
I am also getting this issue on windows 10 with biomod2 v4.2-6-1

generating a new cluster via: 

```
cl <- makeCluster(2)
registerDoParallel(cl)
on.exit(stopCluster(cl))
```

does allow me to run a tuning command
